name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/upload-artifact@v4
        with:
          name: save_file
          path: Climate_Fever/Climate_Fever1.json